### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by MrZyr0** [ynov-b3-2020-nodejs/projet-node-all#1]
We have chosen to use MongoDB as a database. Can you create a base for us @Laroche-Nicolas ?

Thanks

**Comment by Laroche-Nicolas** [comment]
Of course, here is the link of your DB : 
mongodb://heroku_wd3gb88l:cna9uh76nnkb2g71tla2dknkcr@ds135068.mlab.com:35068/heroku_wd3gb88l
